{
 "title": "OTRS - Atendentes",
 "tags": [ "otrs" ],
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "atendente",
    "label": "Atendente",
    "query": "SELECT login FROM users WHERE valid_id = 1 ORDER BY login"
   },
   {
    "name": "questao",
    "label": "Questão",
    "query": "SELECT question FROM survey_question sq JOIN survey s ON (s.id=sq.survey_id AND s.status='Master')"
   }
  ]
 },
 "panels": [
  { "title": "Geral", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Em atendimento",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \nUNIX_TIMESTAMP(ticket.create_time) as time_sec,\nsum(CASE WHEN ticket.ticket_lock_id = 2 THEN 1 ELSE 0 END) as value,\n'locked' as metric\nFROM ticket, users\nWHERE\n    ticket.user_id = users.id\n    AND users.login = '$atendente'\n    AND $__timeFilter(ticket.create_time)\n"
    }
   ]
  },
  {
   "title": "Chamados fechados",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \nUNIX_TIMESTAMP(th.create_time) as time_sec,\ncount(*) as value,\nts.name as metric\nFROM ticket_history th\nJOIN ticket t ON (th.ticket_id=t.id)\nJOIN users u ON (th.owner_id=u.id)\nJOIN ticket_state ts ON (th.state_id=ts.id)\nJOIN ticket_state_type tst ON (ts.type_id=tst.id)\nWHERE\ntst.name = 'closed'\nAND th.history_type_id = 27\nAND u.login = '$atendente'\nAND $__timeFilter(th.create_time)"
    }
   ]
  },
  {
   "title": "Chamados avaliados",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 9, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(sr.create_time) as time_sec,\n  sum(CASE WHEN sr.id THEN 1 ELSE 0 END) as value,\n  'voted' as metric\nFROM survey_request sr\nJOIN ticket t ON (t.id=sr.ticket_id)\nJOIN users u ON (t.user_id=u.id)\nWHERE\nsr.vote_time IS NOT NULL\nAND u.login = \"$atendente\"\nAND $__timeFilter(sr.create_time)"
    }
   ]
  },
  { "title": "Avaliação dos usuários", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "$questao",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
   "repeat": "questao",
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(sv.create_time) as time_sec,\n  count(vote_value) as value,\n  CASE sq.question_type\n    WHEN 'Radio'\n    THEN sa.answer \n    WHEN 'Textarea'\n    THEN REPLACE(sv.vote_value,'$html/text$','')\n    ELSE sv.vote_value\n  END as metric\nFROM survey_vote sv\nLEFT JOIN survey_answer sa ON (sv.vote_value=sa.id)\nJOIN survey_question sq ON (sq.id=sv.question_id)\nJOIN survey_request sr ON (sr.id=sv.request_id)\nJOIN ticket t ON (t.id=sr.ticket_id)\nJOIN users u ON (t.user_id=u.id)\nWHERE\n$__timeFilter(sv.create_time)\nAND sq.question IN ($questao)\nAND u.login = \"$atendente\"\nGROUP BY vote_value\nORDER BY sa.position"
    }
   ]
  },
  {
   "title": "$questao - Chamados avaliados",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 4 },
   "repeat": "questao",
   "targets": [
    {
     "rawSql": "SELECT\n  t.tn,\n  t.title,\n  CASE sq.question_type\n    WHEN 'Radio'\n    THEN sa.answer \n    WHEN 'Textarea'\n    THEN REPLACE(sv.vote_value,'$html/text$','')\n    ELSE sv.vote_value\n  END as answer\nFROM survey_vote sv\nLEFT JOIN survey_answer sa ON (sv.vote_value=sa.id)\nJOIN survey_question sq ON (sq.id=sv.question_id)\nJOIN survey_request sr ON (sv.request_id=sr.id)\nJOIN ticket t ON (t.id=sr.ticket_id)\nJOIN users u ON (u.id=t.user_id)\nWHERE\n$__timeFilter(sv.create_time)\nAND\nsq.question IN ($questao)\nAND\nu.login = \"$atendente\"\nORDER BY t.tn DESC"
    }
   ]
  },
  { "title": "Outros dados", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Ações executadas no OTRS",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT  q.name AS queue_name, t.tn, t.customer_id, t.title,\n        a_t.name AS article_type_name, a.create_time\nFROM    queue AS q, ticket AS t, article AS a, article_type AS a_t, users AS u, (\n            SELECT  _a.ticket_id, MAX(_a.create_time) AS create_time\n            FROM    ticket AS _t, ticket_state AS _t_s, article AS _a\n            WHERE   _t_s.name IN ('new', 'open')\n            AND     _t.ticket_state_id = _t_s.id\n            AND     _a.ticket_id = _t.id\n            GROUP   BY _a.ticket_id\n        ) a_max\nWHERE   q.id = t.queue_id\nAND     t.id = a_max.ticket_id\nAND     a.create_time = a_max.create_time\nAND     a_t.id = a.article_type_id\nAND u.id=a.create_by\nAND $__timeFilter(a.create_time)\nAND u.login = '$atendente'\nGROUP   BY t.id"
    }
   ]
  }
 ]
}